### ISSUE TITLE
Create a Code for BFS in Java

### ISSUE THREAD

**Issue by Burnout-Devil** [Burnout-Devil/HacktoberFest-DSA2022#10]
Dont just copy paste else I will report Your request Invalid.

**Comment by Premjeet1804** [comment]
i code in java please assign me this

**Comment by Premjeet1804** [comment]
!assign me this with hacktoberfest label

**Comment by Premjeet1804** [comment]
Hi,Gooday to you .
i gave a PR for  Breadth First Search Algorithm in java...
please check if ti is correct ...
Thank-you for your vote of confidence...
