### ISSUE TITLE
Given an array nums. We define a running sum of an array as runningSum[i] = sum(nums[0]…nums[i]).  Return the running sum of nums.Input: nums = [1,2,3,4] Output: [1,3,6,10] Explanation: Running sum is obtained as follows: [1, 1+2, 1+2+3, 1+2+3+4].

### ISSUE THREAD

**Issue by SrigiriSruthi** [Burnout-Devil/HacktoberFest-DSA2022#101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SrigiriSruthi** [comment]
@Burnout-Devil can u please assign this to me?

**Comment by utkarshaskumbhar** [comment]
Please assign me this issue

**Comment by Burnout-Devil** [comment]
@utkarshaskumbhar Create your own issue .

**Comment by utkarshaskumbhar** [comment]
Given aaray num of integers that does not contain any zeors, find smallest possible integer m such that -m also exists.return positive integer m 
If there is no such integer return -1

Example:
Num=[4,3,1,7-3,-4,5]
Return 3

**Comment by SrigiriSruthi** [comment]
@Burnout-Devil i have raised a pr. Can u please review it?
