### ISSUE TITLE
Insertion of a node at the beginning of a Linked list

### ISSUE THREAD

**Issue by SrigiriSruthi** [Burnout-Devil/HacktoberFest-DSA2022#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SrigiriSruthi** [comment]
@Burnout-Devil can u please assign me this?

**Comment by Burnout-Devil** [comment]
@SrigiriSruthi these all three are very basic and someone has already submitted these, so try something new.
