### ISSUE TITLE
Write a code of operations of stack 

### ISSUE THREAD

**Issue by Burnout-Devil** [Burnout-Devil/HacktoberFest-DSA2022#39]

**Comment by Razor-5** [comment]
Please assign this to me

**Comment by Ash0069** [comment]
Hi @Burnout-Devil, please assign this to me

**Comment by kr016** [comment]
Hello @Burnout-Devil , can you please assign this issue to me?

**Comment by kanak-chaudhary** [comment]
Hello sir, can you please assign this issue to me.

**Comment by Dishu099** [comment]
Hey @Burnout-Devil can I contribute in this issue or if you want I can make a new issue and then contribute in that.

**Comment by sejal-phatangare** [comment]
Sejal phatangare
Please assign me this issue
