### ISSUE TITLE
Create a code for quick sort

### ISSUE THREAD

**Issue by Burnout-Devil** [Burnout-Devil/HacktoberFest-DSA2022#4]

**Comment by SrigiriSruthi** [comment]
@Burnout-Devil can u please assign this to me?

**Comment by Kallam44** [comment]
@Burnout-Devil I want to solve this Please assign me...

**Comment by Burnout-Devil** [comment]
@SrigiriSruthi  Create a new valid dsa issue i will assign that

**Comment by Burnout-Devil** [comment]
@Kallam44  Create a new valid dsa issue I will assign that.

**Comment by SrigiriSruthi** [comment]
@Burnout-Devil is this fine?

**Comment by Burnout-Devil** [comment]
@SrigiriSruthi  Go to the issues section,there you will find New Issue , Choose that and  then create a issue .

**Comment by SrigiriSruthi** [comment]
@Burnout-Devil can u please check?

**Comment by SrigiriSruthi** [comment]
> @SrigiriSruthi Go to the issues section,there you will find New Issue , Choose that and then create a issue .

done!
