### ISSUE TITLE
adding solution of  code for reversal of array in Python 

### ISSUE THREAD

**Issue by Coder00sharma** [Burnout-Devil/HacktoberFest-DSA2022#46]
Let's array is arr[5] = [10, 20, 30, 40, 50] n = 5
i = 0, j = 4
As (0 is less than 4) swap(arr[0],arr[4])
arr[0]=50 and arr[4]=10, i++(i.,e i=1) and j--(i.e, j=3)
Again (1 is less than 3) swap(arr[1],arr[3])
arr[1]=40 and arr[3]=20, i++(i.,e i=2) and j--(i.e, j=2)

**Comment by niteshjeganathan** [comment]
Hey, Can you please assign this to me
