### ISSUE TITLE
Singly Linked List user input method

### ISSUE THREAD

**Issue by HKRcodes** [Burnout-Devil/HacktoberFest-DSA2022#64]
The Data Structure used here is a singly linked List.
 Here instead of using a predefined linked list, I have used user input system of linked list 
 in which the linked list need not to be predefined and the user can create a linked list and 
 add new nodes to the linked list at the front, rear or any position and can also remove nodes 
 from the front, rear or any position of the linked list.

harikrishnanus2002@gmail.com

**Comment by Ash0069** [comment]
Hi @Burnout-Devil, please assign this issue to me

**Comment by Ris-code** [comment]
Hey, can you please assign me this

**Comment by Vishesh-Vijay** [comment]
pls assign this to me

**Comment by ishita126jain** [comment]
@Burnout-Devil can I contribute to this issue.

**Comment by Burnout-Devil** [comment]
@ishita126jain Create another valid DSA issue
