### ISSUE TITLE
I want to add code for Longest Common Subsequence

### ISSUE THREAD

**Issue by shreya-jpg** [Burnout-Devil/HacktoberFest-DSA2022#70]
I want to add code for Longest Common Subsequence

**Comment by ishita126jain** [comment]
@Burnout-Devil Can I contribute to this issue

**Comment by Burnout-Devil** [comment]
@ishita126jain I cant assign you any issue which is assigned to someone else, you yourself check issues which are already created and create a new issue in issues section, i will assign u that

**Comment by ishita126jain** [comment]
Sure
