### ISSUE TITLE
Reverse the Singly Linked List by taking user input

### ISSUE THREAD

**Issue by ishita126jain** [Burnout-Devil/HacktoberFest-DSA2022#77]
Data Structure used here is sll i.e singly linked list. Instead of predefine linked list here in this problem contributer should make a linked list with user input and then reverse it.Perform certain operation.
1. Make the linked list. 
2. Print the original linked list. 
3. Reverse the list. 
4. Print reversed link list. 
 
This problem can be in any of the language C, C++ , Java, or Python.

**Comment by Burnout-Devil** [comment]
Ok Do it in Java

**Comment by ishita126jain** [comment]
Sure

**Comment by ishita126jain** [comment]
can you check out my PR thankyou
