### ISSUE TITLE
Linked List

### ISSUE THREAD

**Issue by amanydv72** [Burnout-Devil/HacktoberFest-DSA2022#9]
All Operations of linked list

**Comment by amanydv72** [comment]
Please assign this issue to me with hacktoberfest label

**Comment by 123456-manvi** [comment]
[Linked_List.docs.txt](https://github.com/Burnout-Devil/HacktoberFest-DSA2022/files/9803820/Linked_List.docs.txt)

**Comment by Dishu099** [comment]
hey @amanydv72 can I contribute linked list ques in your repo
